name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    # 1. RÃ©cupÃ©ration du code
    - uses: actions/checkout@v4

    # 2. Installation de Node.js
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    # 3. Installation des dÃ©pendances (npm install)
    - name: Install dependencies
      run: npm ci

    # 4. Installation des navigateurs
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # ðŸ‘‡ 5. Ã‰TAPE CRUCIALE AJOUTÃ‰E : GÃ©nÃ©ration du BDD ðŸ‘‡
    - name: Generate BDD Tests
      run: npx bddgen

    # 6. Lancement des tests
    - name: Run Playwright tests
      run: npx playwright test

    # 7. Sauvegarde du rapport
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30s